export const REGISTER_SUCCESS_DOCTOR = "REGISTER_SUCCESS_DOCTOR";
export const REGISTER_FAIL_DOCTOR = "REGISTER_FAIL_DOCTOR";
export const LOGIN_SUCCESS_DOCTOR = "LOGIN_SUCCESS_DOCTOR";
export const LOGIN_FAIL_DOCTOR = "LOGIN_FAIL_DOCTOR";

export const REGISTER_SUCCESS_PATIENT = "REGISTER_SUCCESS_PATIENT";
export const REGISTER_FAIL_PATIENT = "REGISTER_FAIL_PATIENT";
export const LOGIN_SUCCESS_PATIENT = "LOGIN_SUCCESS_PATIENT";
export const LOGIN_FAIL_PATIENT = "LOGIN_FAIL_PATIENT";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
